require 'fileutils'
require 'date'

class QuarterlyAudit
  def initialize(members_dir)
    @members_dir = members_dir
    @current_quarter = get_current_quarter
  end
  
  def run_audit
    puts "Running quarterly audit for #{@current_quarter}..."
    members = get_all_members
    inactive_members = []
    previous_quarter = get_previous_quarter
    
    members.each do |username|
      file_path = File.join(@members_dir, "#{username.downcase}.md")
      next unless File.exist?(file_path)
      
      content = File.read(file_path)
      if !has_contributions_in_quarter?(content, @current_quarter) && !has_contributions_in_quarter?(content, previous_quarter)
        inactive_members << username
      end
    end
    
    puts "Total members: #{members.size}"
    puts "Active members this or previous quarter: #{members.size - inactive_members.size}"
    puts "Inactive members this and previous quarter: #{inactive_members.size}"
    
    if !inactive_members.empty?
      print_inactive_members(inactive_members)
    end
  end
  
  private
  
  def get_current_quarter
    now = Date.today
    quarter = ((now.month - 1) / 3)
    "Q#{quarter} #{now.year}"
  end
  
  def get_all_members
    return [] unless Dir.exist?(@members_dir)
    
    Dir.glob(File.join(@members_dir, "*.md")).map do |file|
      File.basename(file, ".md")
    end
  end
  
  def has_contributions_in_quarter?(content, quarter)
    return false unless content.include?("## #{quarter}")
    quarter_content = content.split("## #{quarter}", 2)[1]
    return false unless quarter_content
    next_section_index = quarter_content.index(/^## /)
    quarter_content = quarter_content[0...next_section_index] if next_section_index
    # Consider any line with a link (http or https) as a contribution
    quarter_content.lines.any? { |line| line =~ /https?:\/\// }
  end
  
  def get_previous_quarter
    now = Date.today
    quarter = ((now.month - 1) / 3) + 1
    year = now.year
    if quarter == 1
      prev_quarter = 4
      year -= 1
    else
      prev_quarter = quarter - 1
    end
    "Q#{prev_quarter} #{year}"
  end
  
  def print_inactive_members(inactive_members)
    puts "INACTIVE_MEMBERS_TITLE=Quarterly Github Audit: Inactive Members for #{@current_quarter}"
    
    puts "INACTIVE_MEMBERS_BODY<<EOF"
    puts "## Inactive Members for #{@current_quarter}\n"
    puts "The following members have no recorded Github contributions this quarter:\n"
    
    inactive_members.each do |username|
      puts "- @#{username}"
    end
    
    puts "\nThis issue was automatically generated by script, it might not be fully correct. Check your file in `/members` and add any missing contributions."
    puts "EOF"
  end
end

if __FILE__ == $0
  members_dir = 'members'
  
  audit = QuarterlyAudit.new(members_dir)
  audit.run_audit
end 
