require 'fileutils'
require 'date'
require 'octokit'

class QuarterlyAudit
  def initialize(members_dir, token, repo)
    @members_dir = members_dir
    @client = Octokit::Client.new(access_token: token)
    @repo = repo
    @current_quarter = get_current_quarter
  end
  
  def run_audit
    puts "Running quarterly audit for #{@current_quarter}..."
    members = get_all_members
    inactive_members = []
    
    members.each do |username|
      file_path = File.join(@members_dir, "#{username.downcase}.md")
      next unless File.exist?(file_path)
      
      content = File.read(file_path)
      if !has_contributions_in_quarter?(content, @current_quarter)
        inactive_members << username
      end
    end
    
    puts "Total members: #{members.size}"
    puts "Active members this quarter: #{members.size - inactive_members.size}"
    puts "Inactive members this quarter: #{inactive_members.size}"
    
    if !inactive_members.empty?
      create_inactive_members_issue(inactive_members)
    end
  end
  
  private
  
  def get_current_quarter
    now = Date.today
    quarter = ((now.month - 1) / 3) + 1
    "Q#{quarter} #{now.year}"
  end
  
  def get_all_members
    return [] unless Dir.exist?(@members_dir)
    
    Dir.glob(File.join(@members_dir, "*.md")).map do |file|
      File.basename(file, ".md")
    end
  end
  
  def has_contributions_in_quarter?(content, quarter)
    return false unless content.include?("## #{quarter}")
    quarter_content = content.split("## #{quarter}")[1]
    
    next_section_index = quarter_content.index(/^## /)
    quarter_content = quarter_content[0...next_section_index] if next_section_index
    quarter_content.match?(/^\* \[/)
  end
  
  #maybe just pass it to the github action to create the issue? 
  def create_inactive_members_issue(inactive_members)
    title = "Quarterly Audit: Inactive Members for #{@current_quarter}"
    
    body = "## Inactive Members for #{@current_quarter}\n\n"
    body += "The following members have no recorded contributions this quarter:\n\n"
    
    inactive_members.each do |username|
      body += "- @#{username}\n"
    end
    
    body += "\nThis issue was automatically generated by the quarterly audit script."
    
    begin
      issue = @client.create_issue(@repo, title, body)
      puts "Created issue ##{issue.number}: #{issue.html_url}"
    rescue => e
      puts "Error creating GitHub issue: #{e.message}"
    end
  end
end

if __FILE__ == $0
  token = ENV['GITHUB_TOKEN']
  members_dir = 'members'
  repo = ENV['GITHUB_REPOSITORY'] || 'your-org/your-repo'
  
  audit = QuarterlyAudit.new(members_dir, token, repo)
  audit.run_audit
end 