name: Daily Activity Tracking

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  track-activity:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'
          bundler-cache: true

      - name: Install dependencies
        run: |
          gem install octokit
          gem install fileutils

      - name: Run Activity Tracker
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CHECK_PERIOD: "24"  
        run: ruby contributions.rb

      - name: Commit changes
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add .
          
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Update user activity tracking [skip ci]"
            git push
          fi
