name: Quarterly Contribution Audit

on:
  workflow_dispatch: 

jobs:
  audit-contributions:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      contents: read
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'
          bundler-cache: true
          
      - name: Install dependencies
        run: bundle install
        
      - name: Run quarterly audit
        id: audit
        run: |
          ruby quarterly_check.rb > audit_output.txt
          echo "AUDIT_OUTPUT<<EOL" >> "$GITHUB_OUTPUT"
          cat audit_output.txt >> "$GITHUB_OUTPUT"
          echo "EOL" >> "$GITHUB_OUTPUT"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
      
      - name: Create issue for inactive members
        if: contains(steps.audit.outputs.AUDIT_OUTPUT, 'INACTIVE_MEMBERS_TITLE')
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const auditOutput = `${{ steps.audit.outputs.AUDIT_OUTPUT }}`;
            
            const titleMatch = auditOutput.match(/INACTIVE_MEMBERS_TITLE=(.*)/);
            const title = titleMatch ? titleMatch[1] : 'Quarterly Audit: Inactive Members';
            
            const bodyStartIndex = auditOutput.indexOf('INACTIVE_MEMBERS_BODY<<EOF') + 'INACTIVE_MEMBERS_BODY<<EOF'.length;
            const bodyEndIndex = auditOutput.indexOf('EOF', bodyStartIndex);
            const body = auditOutput.substring(bodyStartIndex, bodyEndIndex).trim();
            
            if (body) {
              const { owner, repo } = context.repo;
              await github.rest.issues.create({
                owner,
                repo,
                title,
                body
              });
              console.log('Created issue for inactive members');
            } 
