name: Quarterly Contribution Audit

on:
  workflow_dispatch: 

jobs:
  audit-contributions:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      contents: read
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'
          bundler-cache: true
          
      - name: Install dependencies
        run: bundle install
        
      - name: Run quarterly audit
        id: audit
        run: |
          ruby quarterly_check.rb > audit_output.txt
          echo "AUDIT_OUTPUT<<EOL" >> "$GITHUB_OUTPUT"
          cat audit_output.txt >> "$GITHUB_OUTPUT"
          echo "EOL" >> "$GITHUB_OUTPUT"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
      
      - name: Create issue for inactive members
        if: contains(steps.audit.outputs.AUDIT_OUTPUT, 'INACTIVE_MEMBERS_TITLE')
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            try {
              const auditOutput = `${{ steps.audit.outputs.AUDIT_OUTPUT }}`;
              
              // Extract title
              const titleMatch = auditOutput.match(/INACTIVE_MEMBERS_TITLE=(.*)/);
              if (!titleMatch) {
                console.log('No title found in audit output');
                return;
              }
              const title = titleMatch[1];
              
              // Extract body
              const bodyStartIndex = auditOutput.indexOf('INACTIVE_MEMBERS_BODY<<EOF');
              if (bodyStartIndex === -1) {
                console.log('No body start marker found in audit output');
                return;
              }
              
              const bodyStart = bodyStartIndex + 'INACTIVE_MEMBERS_BODY<<EOF'.length;
              const bodyEndIndex = auditOutput.indexOf('EOF', bodyStart);
              if (bodyEndIndex === -1) {
                console.log('No body end marker found in audit output');
                return;
              }
              
              const body = auditOutput.substring(bodyStart, bodyEndIndex).trim();
              if (!body) {
                console.log('No body content found in audit output');
                return;
              }
              
              // Create issue
              const { owner, repo } = context.repo;
              await github.rest.issues.create({
                owner,
                repo,
                title,
                body
              });
              console.log('Successfully created issue for inactive members');
            } catch (error) {
              console.error('Error processing audit output:', error);
              throw error;
            } 
